### ISSUE TITLE
Create attendee sign up page

### ISSUE THREAD

**Issue by vhorvath2010** [KSU-Google-DSC/Google-Summit-Solution#17]
This page should allow users to sign up as attendees for the summit, filling out a form with all necessary information to run the createAttendee API call

**Comment by Sanjay-B** [comment]
Outside of Full name & Email, what other items do we need to collect? @vhorvath2010

**Comment by vhorvath2010** [comment]
We need to collect:

1. Full Name
2. Contact Info (Email/Phone Number, phone number can be an optional field)
3. College they're attending
4. Resume
5. Social Links (GitHub, LinkedIn, etc., let them add as many as they want)
6. Consent to share data with employers

This is what I've gathered from discussions with you and John so far.

**Comment by vhorvath2010** [comment]
> Outside of Full name & Email, what other items do we need to collect? @vhorvath2010

@Sanjay-B 

We need to collect:

1. Full Name
2. Contact Info (Email/Phone Number, phone number can be an optional field)
3. College they're attending
4. Resume
5. Social Links (GitHub, LinkedIn, etc., let them add as many as they want)
6. Consent to share data with employers

This is what I've gathered from discussions with you and John so far.

**Comment by Sanjay-B** [comment]
For #6, I just have a single non-required input for LinkedIn. I figured that Github would probably be on their resume.

**Comment by Sanjay-B** [comment]
Completed as of https://github.com/KSU-Google-DSC/Google-Summit-Solution/pull/25 . cc: @vhorvath2010
